# Generated by Django 3.2.10 on 2022-02-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newtrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
